//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamic_Paint.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynamic_Paint.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a color in which you want to draw shapes.
        /// </summary>
        public static string ColorPickerTooltip {
            get {
                return ResourceManager.GetString("ColorPickerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available colors.
        /// </summary>
        public static string ColorsHeader {
            get {
                return ResourceManager.GetString("ColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DiscardChangesNoButton {
            get {
                return ResourceManager.GetString("DiscardChangesNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Do you want to continue and discard your changes?.
        /// </summary>
        public static string DiscardChangesQuestion {
            get {
                return ResourceManager.GetString("DiscardChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        public static string DiscardChangesTitle {
            get {
                return ResourceManager.GetString("DiscardChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DiscardChangesYesButton {
            get {
                return ResourceManager.GetString("DiscardChangesYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to start drawing ellipsis (mouse drag &amp; drop).
        /// </summary>
        public static string EllipseTooltip {
            get {
                return ResourceManager.GetString("EllipseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string FileMenuExitText {
            get {
                return ResourceManager.GetString("FileMenuExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string FileMenuNewText {
            get {
                return ResourceManager.GetString("FileMenuNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileMenuOpenText {
            get {
                return ResourceManager.GetString("FileMenuOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string FileMenuSaveAsText {
            get {
                return ResourceManager.GetString("FileMenuSaveAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileMenuSaveText {
            get {
                return ResourceManager.GetString("FileMenuSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageMenuEnglishText {
            get {
                return ResourceManager.GetString("LanguageMenuEnglishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string LanguageMenuPolishText {
            get {
                return ResourceManager.GetString("LanguageMenuPolishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageMenuText {
            get {
                return ResourceManager.GetString("LanguageMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to start drawing lines (mouse drag &amp; drop).
        /// </summary>
        public static string LineTooltip {
            get {
                return ResourceManager.GetString("LineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import plugins.
        /// </summary>
        public static string PluginsMenuImportText {
            get {
                return ResourceManager.GetString("PluginsMenuImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginsMenuText {
            get {
                return ResourceManager.GetString("PluginsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to start drawing rectangles (mouse drag &amp; drop).
        /// </summary>
        public static string RectangleTooltip {
            get {
                return ResourceManager.GetString("RectangleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a tool to draw.
        /// </summary>
        public static string StatusDefaultText {
            get {
                return ResourceManager.GetString("StatusDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing an ellipse.
        /// </summary>
        public static string StatusDrawingEllipse {
            get {
                return ResourceManager.GetString("StatusDrawingEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing a line.
        /// </summary>
        public static string StatusDrawingLine {
            get {
                return ResourceManager.GetString("StatusDrawingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing a rectangle.
        /// </summary>
        public static string StatusDrawingRectangle {
            get {
                return ResourceManager.GetString("StatusDrawingRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a thickness of drawn shape.
        /// </summary>
        public static string StrokeThicknessPickerTooltip {
            get {
                return ResourceManager.GetString("StrokeThicknessPickerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test text!.
        /// </summary>
        public static string TestText {
            get {
                return ResourceManager.GetString("TestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to undo your last drawing action.
        /// </summary>
        public static string UndoTooltip {
            get {
                return ResourceManager.GetString("UndoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string UntitledText {
            get {
                return ResourceManager.GetString("UntitledText", resourceCulture);
            }
        }
    }
}
